In [1]:
import site

import pandas as pd
import numpy as np
import warnings
import re

from statsmodels.sandbox.tools.cross_val import split

from utils import *

In [2]:
# raw_abundances = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/only_keeping_data_1_hTERT_HME1_minus10minFC.xlsx", sheet_name='raw_abundances_matrix')
# normalized_abundances = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/only_keeping_data_1_hTERT_HME1_minus10minFC.xlsx", sheet_name='normalized_abundances_matrix')
# stats_normalized = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/only_keeping_data_1_hTERT_HME1_minus10minFC.xlsx", sheet_name='stats_normalized_wide')
# diff_wide = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/only_keeping_data_1_hTERT_HME1_minus10minFC.xlsx", sheet_name='diff_exp_analysis_wide')
# stats_raw = pd.read_excel("Experiment/1_hTERT_HME1/Data/All/only_keeping_data_1_hTERT_HME1_minus10minFC.xlsx", sheet_name='stats_raw_wide')
# FC10min = pd.read_excel("Experiment/1_hTERT_HME1/Data/Processed/Handmade_Log2_FC_from_FGZC_only_10min.xlsx")

In [4]:
# df = pd.merge(raw_abundances, normalized_abundances, on="site", how="left")
# df = pd.merge(df, diff_wide, on="site", how="left")
# df = pd.merge(df, stats_normalized, on="site", how="left")
# df = pd.merge(df, stats_raw, on="site", how="left")
# df = pd.merge(df, FC10min, on="site", how="left")

In [6]:
# df.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Full_dataset_1_hTERT_HME1.xlsx", index=False)

In [11]:
# df = pd.read_excel("Experiment/2_hTERT_HME1/Data/Processed/Full_dataset_2_hTERT_HME1.xlsx")

In [2]:
# sub_data = df[['protein_Id', 'site', 'FC_INS2', 'FC_INS5','FC_INS10', 'FC_INS15', 'FC_INS90']].copy()
# sub_data
#
# lim = 2
# for index, row in sub_data.iterrows():
#     fc_list = row[['FC_INS2', 'FC_INS5','FC_INS10', 'FC_INS15', 'FC_INS90']]
#     if max(fc_list) < lim and abs(min(fc_list)) < lim: #and or abs(min(fc_list)) < 2
#         sub_data.drop(index, inplace=True)
#
# sub_data

In [26]:
# sub_data_sites = list(sub_data["site"].unique())
# proteins = []
# for protein in sub_data_sites:
#     p = protein.split("_")[0]
#     proteins.append(p)
# len(set(proteins))
#
# for protein in set(proteins):
#     print(protein, df.loc[df['protein_Id'] == protein, "description"].unique())

P56211 ['cAMP-regulated phosphoprotein 19 OS=Homo sapiens OX=9606 GN=ARPP19 PE=1 SV=2']
Q9H0G5 ['Nuclear speckle splicing regulatory protein 1 OS=Homo sapiens OX=9606 GN=NSRP1 PE=1 SV=1']
Q86UU1 ['Pleckstrin homology-like domain family B member 1 OS=Homo sapiens OX=9606 GN=PHLDB1 PE=1 SV=1']
Q14980 ['Nuclear mitotic apparatus protein 1 OS=Homo sapiens OX=9606 GN=NUMA1 PE=1 SV=2']
Q7LBC6 ['Lysine-specific demethylase 3B OS=Homo sapiens OX=9606 GN=KDM3B PE=1 SV=2']
Q5SW79 ['Centrosomal protein of 170 kDa OS=Homo sapiens OX=9606 GN=CEP170 PE=1 SV=1']
P08069 ['Insulin-like growth factor 1 receptor OS=Homo sapiens OX=9606 GN=IGF1R PE=1 SV=1']
Q92766 ['Ras-responsive element-binding protein 1 OS=Homo sapiens OX=9606 GN=RREB1 PE=1 SV=3']
Q8N4Q1 ['Mitochondrial intermembrane space import and assembly protein 40 OS=Homo sapiens OX=9606 GN=CHCHD4 PE=1 SV=1']
Q8WWM7 ['Ataxin-2-like protein OS=Homo sapiens OX=9606 GN=ATXN2L PE=1 SV=2']
Q7Z4S6 ['Kinesin-like protein KIF21A OS=Homo sapiens OX=9606 GN=KIF21A PE=1 SV=2']
P49023 ['Paxillin OS=Homo sapiens OX=9606 GN=PXN PE=1 SV=3']
Q12923 ['Tyrosine-protein phosphatase non-receptor type 13 OS=Homo sapiens OX=9606 GN=PTPN13 PE=1 SV=2']
Q5VTQ0 ['Tetratricopeptide repeat protein 39B OS=Homo sapiens OX=9606 GN=TTC39B PE=1 SV=4']
Q9NYT0 ['Pleckstrin-2 OS=Homo sapiens OX=9606 GN=PLEK2 PE=1 SV=1']
P46100 ['Transcriptional regulator ATRX OS=Homo sapiens OX=9606 GN=ATRX PE=1 SV=6']
O43768 ['Alpha-endosulfine OS=Homo sapiens OX=9606 GN=ENSA PE=1 SV=1']
Q14573 ['Inositol 1,4,5-trisphosphate-gated calcium channel ITPR3 OS=Homo sapiens OX=9606 GN=ITPR3 PE=1 SV=2']
O75864 ['Protein phosphatase 1 regulatory subunit 37 OS=Homo sapiens OX=9606 GN=PPP1R37 PE=1 SV=4']
Q9UMD9 ['Collagen alpha-1(XVII) chain OS=Homo sapiens OX=9606 GN=COL17A1 PE=1 SV=3']
Q8N5I9 ['NOP protein chaperone 1 OS=Homo sapiens OX=9606 GN=NOPCHAP1 PE=1 SV=2']
O60343 ['TBC1 domain family member 4 OS=Homo sapiens OX=9606 GN=TBC1D4 PE=1 SV=2']
Q86T82 ['Ubiquitin carboxyl-terminal hydrolase 37 OS=Homo sapiens OX=9606 GN=USP37 PE=1 SV=2']
P31749 ['RAC-alpha serine/threonine-protein kinase OS=Homo sapiens OX=9606 GN=AKT1 PE=1 SV=2']
P54727 ['UV excision repair protein RAD23 homolog B OS=Homo sapiens OX=9606 GN=RAD23B PE=1 SV=1']
Q09666 ['Neuroblast differentiation-associated protein AHNAK OS=Homo sapiens OX=9606 GN=AHNAK PE=1 SV=2']
O95817 ['BAG family molecular chaperone regulator 3 OS=Homo sapiens OX=9606 GN=BAG3 PE=1 SV=3']
Q9BW04 ['Specifically androgen-regulated gene protein OS=Homo sapiens OX=9606 GN=SARG PE=1 SV=2']
P13639 ['Elongation factor 2 OS=Homo sapiens OX=9606 GN=EEF2 PE=1 SV=4']
Q9NQW6 ['Anillin OS=Homo sapiens OX=9606 GN=ANLN PE=1 SV=2']
P27361 ['Mitogen-activated protein kinase 3 OS=Homo sapiens OX=9606 GN=MAPK3 PE=1 SV=4']
Q8WYP5 ['Protein ELYS OS=Homo sapiens OX=9606 GN=AHCTF1 PE=1 SV=3']
Q92997 ['Segment polarity protein dishevelled homolog DVL-3 OS=Homo sapiens OX=9606 GN=DVL3 PE=1 SV=2']

In [24]:
# df_1 = pd.read_excel("Experiment/2_hTERT_HME1/Data/Processed/full_starve_continuous_FC_nrep_SD.xlsx")

In [3]:

# subset = df_1.loc[df_1['site'].isin(sub_data_sites)]
#
# warnings.filterwarnings('ignore')
#
# plot_dataset_phosphosites(df=subset,
#                           legend = ['1.57 nM EGF', '100 nM INS', '1.57 nM EGF+ 100 nM INS'], x_axis=['Full', 'Starve', '2', '5', '10', '15', '90'], color_palette = ['r', 'b', 'fuchsia'],
#                           saving_path = "", dataset_name= "", saving_info="",
#                           plot_individually = False, fit_y_lims=False,  plot_close=False,
#                           save_pdf=False, save_png=False)

In [3]:
# print(select(options=True))
# print(select(key = "log2_abundances", options = False))

dict_keys(['raw_abundances', 'log2_abundances', 'mean_raw_abundances', 'median_raw_abundances', 'CV_raw_abundances', 'mean_log2_abundances', 'median_log2_abundances', 'sd_log2_abundances', 'var_log2_abundances', 'FC', 'FC_pvalues', 'FC_FDR', 'FC_stats', 'others'])
['EGF_full_r1', 'EGF_full_r2', 'EGF_full_r3', 'EGF_full_r4', 'EGF_starve_r1', 'EGF_starve_r2', 'EGF_starve_r3', 'EGF_starve_r4', 'EGF2_r1', 'EGF2_r2', 'EGF2_r3', 'EGF2_r4', 'EGF5_r1', 'EGF5_r2', 'EGF5_r3', 'EGF5_r4', 'EGF10_r1', 'EGF10_r2', 'EGF10_r3', 'EGF10_r4', 'EGF15_r1', 'EGF15_r2', 'EGF15_r3', 'EGF15_r4', 'EGF90_r1', 'EGF90_r2', 'EGF90_r3', 'EGF90_r4', 'INS_full_r1', 'INS_full_r2', 'INS_full_r3', 'INS_full_r4', 'INS_starve_r1', 'INS_starve_r2', 'INS_starve_r3', 'INS_starve_r4', 'INS2_r1', 'INS2_r2', 'INS2_r3', 'INS2_r4', 'INS5_r1', 'INS5_r2', 'INS5_r3', 'INS5_r4', 'INS10_r1', 'INS10_r2', 'INS10_r3', 'INS10_r4', 'INS15_r1', 'INS15_r2', 'INS15_r3', 'INS15_r4', 'INS90_r1', 'INS90_r2', 'INS90_r3', 'INS90_r4', 'EGFnINS_full_r1', 'EGFnINS_full_r2', 'EGFnINS_full_r3', 'EGFnINS_full_r4', 'EGFnINS_starve_r1', 'EGFnINS_starve_r2', 'EGFnINS_starve_r3', 'EGFnINS_starve_r4', 'EGFnINS2_r1', 'EGFnINS2_r2', 'EGFnINS2_r3', 'EGFnINS2_r4', 'EGFnINS5_r1', 'EGFnINS5_r2', 'EGFnINS5_r3', 'EGFnINS5_r4', 'EGFnINS10_r1', 'EGFnINS10_r2', 'EGFnINS10_r3', 'EGFnINS10_r4', 'EGFnINS15_r1', 'EGFnINS15_r2', 'EGFnINS15_r3', 'EGFnINS15_r4', 'EGFnINS90_r1', 'EGFnINS90_r2', 'EGFnINS90_r3', 'EGFnINS90_r4']

# ChatGPT code to merge functinoal score and ERK motif information to the dataframe

In [16]:
# df = pd.read_excel("Experiment/1_hTERT_HME1/Data/Processed/Full_dataset_1_hTERT_HME1_functional_names_diff_scaled.xlsx")
# phosphosite_plus = pd.read_csv("External_Data/PhosphoSitePlus.txt", sep="\t")

In [17]:
df

,protein_Id,protein_name,site,raw_abs_EGF_full_r1,raw_abs_EGF_full_r2,raw_abs_EGF_full_r3,raw_abs_EGF_full_r4,raw_abs_EGF_starve_r1,raw_abs_EGF_starve_r2,raw_abs_EGF_starve_r3,...,FC_scaled_INS_5,FC_scaled_INS_10,FC_scaled_INS_90,FC_scaled_EGFnINS_full,FC_scaled_EGFnINS_starve,FC_scaled_EGFnINS_1,FC_scaled_EGFnINS_2,FC_scaled_EGFnINS_5,FC_scaled_EGFnINS_10,FC_scaled_EGFnINS_90
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,0.000000e+00,3.413601e+04,0.000000e+00,0.000000e+00,0.000000,11970.095745,0.000000,...,0.062765,-0.053044,0.392610,1.000000,0,0.009989,0.027808,0.150342,0.266855,0.384599
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.526291e+06,3.107422e+06,2.844213e+06,2.838165e+06,462877.845884,406460.086218,466606.366000,...,0.179028,0.290848,0.460393,1.000000,0,-0.013889,0.076752,0.324961,0.489716,0.582838
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,2.538396e+05,2.912180e+05,1.878137e+05,2.302995e+05,370294.907420,351169.823470,391574.055743,...,-0.255660,-0.346432,-0.518686,-0.960321,0,-0.298015,-0.083473,-0.121019,-0.236009,-1.000000
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,0.000000e+00,3.436628e+04,0.000000e+00,3.184211e+04,0.000000,36947.507319,0.000000,...,-0.101023,-0.349209,-0.490396,-0.873135,0,-0.473961,0.472592,-0.426896,1.000000,-0.556594
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.004880e+05,5.070251e+05,2.948686e+05,0.000000e+00,732858.964004,703950.993495,706990.737660,...,-0.463319,-0.694263,-0.725995,-0.968252,0,-0.433320,-0.418878,-0.566253,-0.678022,-0.971486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.612031e+04,3.523211e+04,2.328310e+04,2.882678e+04,28158.918559,31337.999945,38445.424548,...,-0.237642,-0.229769,-0.326227,0.213563,0,0.339692,-0.197463,0.293183,0.357531,0.632659
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,0.000000e+00,0.000000e+00,0.000000e+00,1.989511e+04,0.000000,0.000000,0.000000,...,-0.272567,-0.010828,-0.409369,-1.000000,0,-0.677587,0.251546,-0.903483,-0.073504,-0.696452
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.252726e+05,2.548493e+05,1.697470e+05,1.780225e+05,202512.144807,165807.326109,237987.604392,...,0.496345,1.000000,0.353154,0.470627,0,0.341903,0.492076,0.097209,0.917837,0.303394
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,0.000000e+00,0.000000e+00,3.689021e+03,0.000000e+00,0.000000,0.000000,5253.875296,...,-0.193603,0.050333,-0.288665,-0.153054,0,-1.000000,0.300186,0.197979,0.221990,-0.289061
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,7.302473e+04,1.077101e+05,0.000000e+00,0.000000e+00,94711.843842,83686.478536,0.000000,...,1.000000,-0.333083,0.109390,-0.067173,0,-0.159262,0.195586,0.047995,-0.064721,0.256252

In [19]:
phosphosite_plus

,uniprot,gene,prot_seq_position,aa,site,functional_score,ms_lit,ERK_motif,ERK_ext_motif
0,Q9NQ94,A1CF,12,S,HKSGDGLsGTQKEAA,NaN,1.0,False,False
1,Q9NQ94,A1CF,186,Y,RGFAFVEyESHRAAA,NaN,NaN,False,False
2,Q9NQ94,A1CF,313,T,KDSYVRYtRGTGGRG,NaN,NaN,False,False
3,Q9NQ94,A1CF,401,Y,RGLGGRGyLAYTGLG,NaN,NaN,False,False
4,Q9NQ94,A1CF,404,Y,GGRGYLAyTGLGRGY,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...
265165,Q8IYH5,ZZZ3,474,S,PSAKESAsQHITEEE,0.172121,1.0,False,False
265166,Q8IYH5,ZZZ3,606,S,GLPARPKsPLDPKKD,0.538854,6.0,True,True
265167,Q8IYH5,ZZZ3,670,Y,LEQLLIKyPPEEVES,NaN,NaN,False,False
265168,Q8IYH5,ZZZ3,677,S,YPPEEVEsRRWQKIA,NaN,NaN,False,False
265169,Q8IYH5,ZZZ3,777,S,NTAVEDAsDDESIPI,0.183961,2.0,False,False

In [5]:
# code from chatgpt to be able to merge my dataset to the phosphositeplus datase

import re
import pandas as pd
from pandas.api.types import is_numeric_dtype

def _extract_all_ints(x):
    """Return list of all integers in a string; empty list if none."""
    if pd.isna(x):
        return []
    return [int(n) for n in re.findall(r'(\d+)', str(x))]

def _extract_first_int(x):
    """Return the first integer in a string; None if none."""
    if pd.isna(x):
        return None
    m = re.search(r'(\d+)', str(x))
    return int(m.group(1)) if m else None

def _infer_sites_from_peptide(peptide, site_start):
    """
    Infer absolute protein positions from lowercase phospho residues (s/t/y) in Peptide.
    site_start is 1-based (typical). Returns list of ints.
    """
    if pd.isna(peptide) or pd.isna(site_start):
        return []
    pep = str(peptide)
    # positions of lowercase s/t/y in peptide (0-based)
    idxs = [i for i, ch in enumerate(pep) if ch in "sty"]
    # absolute protein positions (1-based site_start + idx)
    try:
        start = int(site_start)
    except Exception:
        return []
    return [start + i for i in idxs]

def _concat_unique(series, sep="; "):
    vals = [str(v) for v in series if pd.notna(v) and str(v) != ""]
    if not vals:
        return pd.NA
    uniq = list(dict.fromkeys(vals))  # preserve order, remove dups
    return sep.join(uniq)

def _coerce_numeric_safe(s):
    """Coerce to numeric when possible; otherwise return original series."""
    try:
        out = pd.to_numeric(s, errors="coerce")
        # If everything became NaN and original had non-numeric, keep original.
        if out.notna().sum() == 0 and s.notna().sum() > 0:
            return s
        return out
    except Exception:
        return s

def annotate_with_phosphosite_like(
    df_main: pd.DataFrame,
    df_new: pd.DataFrame,
    *,
    add_cols=("functional_score", "ms_lit", "ERK_motif", "ERK_ext_motif"),
    main_protein_col="protein_Id",
    main_gene_col="protein_name",
    main_site_col="phospho_sites",
    main_peptide_col="Peptide",
    main_site_start_col="site_start",
    new_uniprot_col="uniprot",
    new_gene_col="gene",
    new_pos_col="prot_seq_position",
    enforce_gene_match=False,
):
    """
    Add annotations from df_new to df_main WITHOUT creating new rows in df_main.
    Matching keys: (protein_Id == uniprot) and site number (from main phospho_sites OR inferred from Peptide).
    df_new may contain duplicate (uniprot, site) rows; we deterministically keep the 'best' one.

    Returns: df_out (same shape/order as df_main) with added columns.
    """

    # ---------- 1) Build unique site-level lookup from df_new ----------
    dfB = df_new.copy()
    # parse numeric site & residue letter
    dfB["_site_pos"] = dfB[new_pos_col].apply(_extract_first_int)
    dfB["_residue"] = dfB[new_pos_col].astype(str).str.extract(r'([STY])', expand=False)

    # keep only relevant columns that exist
    keep_new = [new_uniprot_col, new_gene_col, "_site_pos", "_residue"] + [c for c in add_cols if c in dfB.columns]
    dfB = dfB[[c for c in keep_new if c in dfB.columns]].copy()

    # tie-breaker sorting: prefer rows with higher functional_score, then ms_lit/ERK flags
    # (coerce to numeric/bool-ish so sorting works)
    if "functional_score" in dfB.columns:
        dfB["__fs__"] = _coerce_numeric_safe(dfB["functional_score"]).fillna(float("-inf"))
    else:
        dfB["__fs__"] = float("-inf")
    for flag in ("ms_lit", "ERK_motif", "ERK_ext_motif"):
        if flag in dfB.columns:
            dfB[f"__{flag}__"] = _coerce_numeric_safe(dfB[flag]).fillna(0)
        else:
            dfB[f"__{flag}__"] = 0

    # sort: best first
    dfB = dfB.sort_values(
        by=["__fs__", "__ms_lit__", "__ERK_motif__", "__ERK_ext_motif__"],
        ascending=[False, False, False, False],
        kind="mergesort",  # stable
    )

    # drop duplicates to one row per (uniprot, site)
    dfB_unique = dfB.drop_duplicates(subset=[new_uniprot_col, "_site_pos"], keep="first").copy()

    # cleanup temp columns
    dfB_unique = dfB_unique.drop(columns=[c for c in dfB_unique.columns if c.startswith("__")], errors="ignore")

    # ---------- 2) Prepare df_main: get site list per row ----------
    dfA = df_main.copy()
    dfA["_orig_index"] = dfA.index

    # primary: parse numeric sites from main_site_col
    site_lists = dfA[main_site_col].apply(_extract_all_ints)

    # fallback: if empty list, infer from peptide + site_start
    need_infer = site_lists.apply(len).eq(0)
    if need_infer.any():
        inferred = [
            _infer_sites_from_peptide(peptide, start)
            for peptide, start in zip(dfA.loc[need_infer, main_peptide_col], dfA.loc[need_infer, main_site_start_col])
        ]
        # fill where empty
        j = 0
        new_site_lists = []
        for i, lst in enumerate(site_lists):
            if len(lst) == 0:
                new_site_lists.append(inferred[j])
                j += 1
            else:
                new_site_lists.append(lst)
        site_lists = pd.Series(new_site_lists, index=dfA.index)

    dfA["_site_list"] = site_lists
    # explode to site-level rows (but keep rows with no sites to preserve index)
    dfA_exp = dfA.explode("_site_list", ignore_index=False).rename(columns={"_site_list": "_site_pos"}).reset_index(drop=True)

    # ---------- 3) Merge at site-level, then collapse back ----------
    merged = pd.merge(
        dfA_exp,
        dfB_unique,
        left_on=[main_protein_col, "_site_pos"],
        right_on=[new_uniprot_col, "_site_pos"],
        how="left",
        copy=False,
    )

    # Optionally blank annotations if gene disagrees
    if enforce_gene_match and (new_gene_col in merged.columns):
        ok = merged[new_gene_col].isna() | (merged[new_gene_col] == merged[main_gene_col])
        for c in add_cols:
            if c in merged.columns:
                merged.loc[~ok, c] = pd.NA

    # Aggregation rules to collapse back to original rows
    agg_funcs = {}
    for c in add_cols:
        if c in merged.columns:
            col = merged[c]
            if is_numeric_dtype(col):
                agg_funcs[c] = "max"  # take the strongest / any positive
            else:
                # treat as flag-like or text: OR-like for 0/1, else concat unique
                # try numeric OR
                try_num = pd.to_numeric(col, errors="coerce")
                if try_num.notna().any():
                    agg_funcs[c] = "max"
                else:
                    agg_funcs[c] = _concat_unique

    collapsed = (
        merged.groupby("_orig_index", sort=False)[list(agg_funcs.keys())]
              .agg(agg_funcs)
              .reindex(df_main.index)
    )

    # ---------- 4) Attach to original df ----------
    out = df_main.copy()
    for c in add_cols:
        out[c] = collapsed[c] if c in collapsed.columns else pd.NA

    return out

# ---------------- Example usage ----------------
# df_main = pd.read_excel("/mnt/data/small_subset_for_ChatGPT.xlsx", sheet_name="Sheet1")
# df_new  = pd.read_excel("/mnt/data/Phosphosite_plus_subset.xlsx")
# df_merged = annotate_with_phosphosite_like(df_main, df_new, add_cols=("functional_score","ms_lit","ERK_motif","ERK_ext_motif"))
# df_merged.head()

In [38]:
#cahtgpt code. the dataframe from experiment 1 htert HME1 had no row "phospho_sites" and was giving problem to merge the dataset with phosphosite plus data. this code check in the site column if there are localized phosphosites. and creates a new column

def extract_found_phosphosites(site_val):
    """
    From a 'site' string:
      - Split on '_' and '~'
      - If parts[4] == '0' -> no localized site -> return <NA>
      - Else parts[5] contains localized phosphosite(s)
        - Normalize to 'S##;T##;Y##' if concatenated (e.g., 'S48T888Y45')
    """
    if pd.isna(site_val):
        return pd.NA

    parts = re.split(r'[_~]', str(site_val))
    # Need at least 6 parts to access indices 4 and 5 safely
    if len(parts) <= 4:
        return pd.NA

    flag = parts[4].strip()
    if flag == "0":
        return pd.NA

    token = parts[5].strip() if len(parts) > 5 else ""
    if not token:
        return pd.NA

    # Normalize case and split concatenated residues like S48T888Y45 -> ['S48','T888','Y45']
    token_up = token.upper()
    matches = re.findall(r'(?:[STY])\d+', token_up)

    if matches:
        return ";".join(matches)

    # Fallback: try generic <Letter><digits> patterns if non-STY letters appear
    generic = re.findall(r'([A-Z])(\d+)', token_up)
    if generic:
        return ";".join([f"{a}{b}" for a, b in generic])

    # If nothing matches, return as-is (rare)
    return token

# Create the new column
df["phospho_sites"] = df["site"].apply(extract_found_phosphosites)

In [41]:
# df.fillna("", inplace=True)

                                                  site phospho_sites
0                    A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR          <NA>
1               A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR          S154
2            A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR          <NA>
3       A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR          S264
4       A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR          S266
...                                                ...           ...
34997           Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK          S338
34998       Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR          <NA>
34999  Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR          S338
35000      Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK          <NA>
35001                 Q9Y6Y8_728_728_1_1_S728~GQEQsAQK          S728

[35002 rows x 2 columns]

In [42]:
df_main = df.copy()
df_new  = phosphosite_plus.copy()
df_merged = annotate_with_phosphosite_like(df_main, df_new, add_cols=("functional_score","ms_lit","ERK_motif","ERK_ext_motif"))
df_merged

,protein_Id,protein_name,site,raw_abs_EGF_full_r1,raw_abs_EGF_full_r2,raw_abs_EGF_full_r3,raw_abs_EGF_full_r4,raw_abs_EGF_starve_r1,raw_abs_EGF_starve_r2,raw_abs_EGF_starve_r3,...,FC_scaled_EGFnINS_1,FC_scaled_EGFnINS_2,FC_scaled_EGFnINS_5,FC_scaled_EGFnINS_10,FC_scaled_EGFnINS_90,phospho_sites,functional_score,ms_lit,ERK_motif,ERK_ext_motif
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,0.000000e+00,3.413601e+04,0.000000e+00,0.000000e+00,0.000000,11970.095745,0.000000,...,0.009989,0.027808,0.150342,0.266855,0.384599,<NA>,NaN,NaN,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.526291e+06,3.107422e+06,2.844213e+06,2.838165e+06,462877.845884,406460.086218,466606.366000,...,-0.013889,0.076752,0.324961,0.489716,0.582838,S154,NaN,NaN,NaN,NaN
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,2.538396e+05,2.912180e+05,1.878137e+05,2.302995e+05,370294.907420,351169.823470,391574.055743,...,-0.298015,-0.083473,-0.121019,-0.236009,-1.000000,<NA>,NaN,NaN,NaN,NaN
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,0.000000e+00,3.436628e+04,0.000000e+00,3.184211e+04,0.000000,36947.507319,0.000000,...,-0.473961,0.472592,-0.426896,1.000000,-0.556594,S264,NaN,NaN,NaN,NaN
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.004880e+05,5.070251e+05,2.948686e+05,0.000000e+00,732858.964004,703950.993495,706990.737660,...,-0.433320,-0.418878,-0.566253,-0.678022,-0.971486,S266,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.612031e+04,3.523211e+04,2.328310e+04,2.882678e+04,28158.918559,31337.999945,38445.424548,...,0.339692,-0.197463,0.293183,0.357531,0.632659,S338,0.588318,18.0,False,False
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,0.000000e+00,0.000000e+00,0.000000e+00,1.989511e+04,0.000000,0.000000,0.000000,...,-0.677587,0.251546,-0.903483,-0.073504,-0.696452,<NA>,NaN,NaN,NaN,NaN
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.252726e+05,2.548493e+05,1.697470e+05,1.780225e+05,202512.144807,165807.326109,237987.604392,...,0.341903,0.492076,0.097209,0.917837,0.303394,S338,0.588318,18.0,False,False
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,0.000000e+00,0.000000e+00,3.689021e+03,0.000000e+00,0.000000,0.000000,5253.875296,...,-1.000000,0.300186,0.197979,0.221990,-0.289061,<NA>,NaN,NaN,NaN,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,7.302473e+04,1.077101e+05,0.000000e+00,0.000000e+00,94711.843842,83686.478536,0.000000,...,-0.159262,0.195586,0.047995,-0.064721,0.256252,S728,0.096860,NaN,False,False

,protein_Id,protein_name,site,raw_abs_EGF_full_r1,raw_abs_EGF_full_r2,raw_abs_EGF_full_r3,raw_abs_EGF_full_r4,raw_abs_EGF_starve_r1,raw_abs_EGF_starve_r2,raw_abs_EGF_starve_r3,...,FC_scaled_EGFnINS_starve,FC_scaled_EGFnINS_1,FC_scaled_EGFnINS_2,FC_scaled_EGFnINS_5,FC_scaled_EGFnINS_10,FC_scaled_EGFnINS_90,functional_score,ms_lit,ERK_motif,ERK_ext_motif
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,0.000000e+00,3.413601e+04,0.000000e+00,0.000000e+00,0.000000,11970.095745,0.000000,...,0,0.009989,0.027808,0.150342,0.266855,0.384599,NaN,NaN,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.526291e+06,3.107422e+06,2.844213e+06,2.838165e+06,462877.845884,406460.086218,466606.366000,...,0,-0.013889,0.076752,0.324961,0.489716,0.582838,NaN,NaN,NaN,NaN
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,2.538396e+05,2.912180e+05,1.878137e+05,2.302995e+05,370294.907420,351169.823470,391574.055743,...,0,-0.298015,-0.083473,-0.121019,-0.236009,-1.000000,NaN,NaN,NaN,NaN
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,0.000000e+00,3.436628e+04,0.000000e+00,3.184211e+04,0.000000,36947.507319,0.000000,...,0,-0.473961,0.472592,-0.426896,1.000000,-0.556594,NaN,NaN,NaN,NaN
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.004880e+05,5.070251e+05,2.948686e+05,0.000000e+00,732858.964004,703950.993495,706990.737660,...,0,-0.433320,-0.418878,-0.566253,-0.678022,-0.971486,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.612031e+04,3.523211e+04,2.328310e+04,2.882678e+04,28158.918559,31337.999945,38445.424548,...,0,0.339692,-0.197463,0.293183,0.357531,0.632659,NaN,NaN,NaN,NaN
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,0.000000e+00,0.000000e+00,0.000000e+00,1.989511e+04,0.000000,0.000000,0.000000,...,0,-0.677587,0.251546,-0.903483,-0.073504,-0.696452,NaN,NaN,NaN,NaN
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.252726e+05,2.548493e+05,1.697470e+05,1.780225e+05,202512.144807,165807.326109,237987.604392,...,0,0.341903,0.492076,0.097209,0.917837,0.303394,NaN,NaN,NaN,NaN
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,0.000000e+00,0.000000e+00,3.689021e+03,0.000000e+00,0.000000,0.000000,5253.875296,...,0,-1.000000,0.300186,0.197979,0.221990,-0.289061,NaN,NaN,NaN,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,7.302473e+04,1.077101e+05,0.000000e+00,0.000000e+00,94711.843842,83686.478536,0.000000,...,0,-0.159262,0.195586,0.047995,-0.064721,0.256252,NaN,NaN,NaN,NaN

In [48]:
# df_merged.to_excel("Experiment/1_hTERT_HME1/Data/Processed/Full_dataset_1_hTERT_HME1_functional_names_diff_scaled_phPlus.xlsx", index=False)
df_merged

,protein_Id,protein_name,site,raw_abs_EGF_full_r1,raw_abs_EGF_full_r2,raw_abs_EGF_full_r3,raw_abs_EGF_full_r4,raw_abs_EGF_starve_r1,raw_abs_EGF_starve_r2,raw_abs_EGF_starve_r3,...,FC_scaled_EGFnINS_1,FC_scaled_EGFnINS_2,FC_scaled_EGFnINS_5,FC_scaled_EGFnINS_10,FC_scaled_EGFnINS_90,phospho_sites,functional_score,ms_lit,ERK_motif,ERK_ext_motif
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,0.000000e+00,3.413601e+04,0.000000e+00,0.000000e+00,0.000000,11970.095745,0.000000,...,0.009989,0.027808,0.150342,0.266855,0.384599,<NA>,NaN,NaN,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,2.526291e+06,3.107422e+06,2.844213e+06,2.838165e+06,462877.845884,406460.086218,466606.366000,...,-0.013889,0.076752,0.324961,0.489716,0.582838,S154,NaN,NaN,NaN,NaN
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,2.538396e+05,2.912180e+05,1.878137e+05,2.302995e+05,370294.907420,351169.823470,391574.055743,...,-0.298015,-0.083473,-0.121019,-0.236009,-1.000000,<NA>,NaN,NaN,NaN,NaN
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,0.000000e+00,3.436628e+04,0.000000e+00,3.184211e+04,0.000000,36947.507319,0.000000,...,-0.473961,0.472592,-0.426896,1.000000,-0.556594,S264,NaN,NaN,NaN,NaN
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,4.004880e+05,5.070251e+05,2.948686e+05,0.000000e+00,732858.964004,703950.993495,706990.737660,...,-0.433320,-0.418878,-0.566253,-0.678022,-0.971486,S266,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,3.612031e+04,3.523211e+04,2.328310e+04,2.882678e+04,28158.918559,31337.999945,38445.424548,...,0.339692,-0.197463,0.293183,0.357531,0.632659,S338,0.588318,18.0,False,False
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,0.000000e+00,0.000000e+00,0.000000e+00,1.989511e+04,0.000000,0.000000,0.000000,...,-0.677587,0.251546,-0.903483,-0.073504,-0.696452,<NA>,NaN,NaN,NaN,NaN
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,2.252726e+05,2.548493e+05,1.697470e+05,1.780225e+05,202512.144807,165807.326109,237987.604392,...,0.341903,0.492076,0.097209,0.917837,0.303394,S338,0.588318,18.0,False,False
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,0.000000e+00,0.000000e+00,3.689021e+03,0.000000e+00,0.000000,0.000000,5253.875296,...,-1.000000,0.300186,0.197979,0.221990,-0.289061,<NA>,NaN,NaN,NaN,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,7.302473e+04,1.077101e+05,0.000000e+00,0.000000e+00,94711.843842,83686.478536,0.000000,...,-0.159262,0.195586,0.047995,-0.064721,0.256252,S728,0.096860,NaN,False,False

In [46]:
display_columns = ['protein_Id', 'protein_name', 'site', 'phospho_sites', 'functional_score', 'ms_lit', 'ERK_motif', 'ERK_ext_motif']
subdata = df_merged[display_columns].copy()
subdata

,protein_Id,protein_name,site,phospho_sites,functional_score,ms_lit,ERK_motif,ERK_ext_motif
0,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_0~SGSGNFGGGR,<NA>,NaN,NaN,NaN,NaN
1,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_152_154_1_1_S154~SGsGNFGGGR,S154,NaN,NaN,NaN,NaN
2,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_0~NQGGYGGSSSSSSYGSGR,<NA>,NaN,NaN,NaN,NaN
3,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S264~NQGGYGGSsSSSSYGSGR,S264,NaN,NaN,NaN,NaN
4,A0A2R8Y4L2,HNRNPA1L3,A0A2R8Y4L2_260_271_1_1_S266~NQGGYGGSSSsSSYGSGR,S266,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
34997,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_338_1_1_S338~SLsFEMQQDELIEK,S338,0.588318,18.0,False,False
34998,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_0~SLSFEMQQDELIEKPMSPMQYAR,<NA>,NaN,NaN,NaN,NaN
34999,Q9Y6Y0,IVNS1ABP,Q9Y6Y0_336_356_1_1_S338~SLsFEMQQDELIEKPMSPMQYAR,S338,0.588318,18.0,False,False
35000,Q9Y6Y8,SEC23IP,Q9Y6Y8_118_138_1_0~PLTALPFTTGSQDVSNAFSPSISK,<NA>,NaN,NaN,NaN,NaN
35001,Q9Y6Y8,SEC23IP,Q9Y6Y8_728_728_1_1_S728~GQEQsAQK,S728,0.096860,NaN,False,False

In [36]:
protein = "EGFR"

In [50]:
# subdata.loc[subdata["protein_name"] == protein]

In [49]:
# phosphosite_plus.loc[phosphosite_plus["gene"] == protein]