In [158]:
import pandas as pd
from jupyter_core.migrate import regex

from utils import *

In [128]:
df_combined = pd.read_csv("Experiment/3_hTERT_HME1_mutants_comparison/Data/Processed/combined_modified_peptide_renamed.txt", sep="\t")
df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,BRAFS151A_localization_EGF_10_r2,BRAFS151A_localization_EGF_25_r1,BRAFS151A_localization_EGF_25_r2,GAB1Y259A_localization_EGF_starve_r1,GAB1Y259A_localization_EGF_2_r1,GAB1Y259A_localization_EGF_2_r2,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.3985)AGGKEAAS(...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6939)AGGKEAAS(...,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,M:15.9949@VSVINTVDTSHEDM(0.8966)IHDAQM(0.1034)...,NaN,M:15.9949@VSVINTVDTSHEDM(0.9445)IHDAQM(0.0555)...,M:15.9949@VSVINTVDTSHEDM(0.9210)IHDAQM(0.0790)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,NaN,NaN,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,n:42.0106@n(1.0000)WQGSNLGGTPVTHCK;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,n:42.0106@n(1.0000)YRDPEAASPGAPSR;,NaN,NaN,NaN

In [129]:
# Re define some columns for how many sites are localized, which type of modification was localized and how many
# Number of modifications localized
df_combined["n_localized"] = df_combined["Assigned_Modifications"].str.split(",").str.len().fillna(0).astype(int)

# Number of SYT modification localized
df_combined["STY_localized"] = (df_combined["Assigned_Modifications"]
                                .str.split(",")
                                .apply(lambda x: sum(any(c in item for c in "TYS") for item in x) if isinstance(x, list) else 0)
                                )

# Number of other modifications localized
df_combined["other_localized"] = (df_combined["Assigned_Modifications"]
                                .str.split(",")
                                .apply(lambda x: sum(not any(c in item for c in "TYS") for item in x) if isinstance(x, list) else 0)
                                )

# True or False if all modifications where localized (both STY and other)
df_combined["all_localized"] = df_combined["STY_localized"].astype(int) + df_combined["other_localized"].astype(int) == df_combined["Charges"].str.split(",").str[0].astype(int)

# Re-anotation for the modifications localization
df_combined["Assigned_Modifications_clean"] = df_combined["Assigned_Modifications"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_combined["Assigned_Modifications_clean"] = df_combined["Assigned_Modifications_clean"].str.replace(r"\b(\d+)([A-Za-z])\b",r"\2\1",regex=True)
df_combined["Assigned_Modifications_clean"] = df_combined["Assigned_Modifications_clean"].str.replace(r",", "", regex=True)

# Create the site column with all the information
df_combined["site"] = (df_combined["protein_Id"].astype(str)+"_"
                       +df_combined["site_start"].astype(str)+"_"
                       +df_combined["site_end"].astype(str)+"_"
                       +df_combined["n_localized"].astype(str)+"_"
                       +df_combined["STY_localized"].astype(str)+"_"
                       +df_combined["all_localized"].astype(str)+"_"
                       +df_combined["Assigned_Modifications_clean"])

df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2,n_localized,STY_localized,other_localized,all_localized,Assigned_Modifications_clean,site
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,NaN,NaN,NaN,NaN,2,2,0,True,S25S30,P0CG40_455_484_2_2_True_S25S30
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,1,1,0,False,S17,P0CG40_455_475_1_1_False_S17
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,2,2,0,True,S17S25,P0CG40_455_484_2_2_True_S17S25
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,0,0,0,False,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,NaN,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,2,2,0,True,S20S24,Q8WXD9_1345_1370_2_2_True_S20S24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,2,0,2,False,N-termM14,P55735_2_27_2_0_False_N-termM14
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,3,0,3,True,N-termM14M20,P55735_2_27_3_0_True_N-termM14M20
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,NaN,NaN,NaN,2,0,2,True,N-termC14,rev_Q17R98_2_16_2_0_True_N-termC14
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,5,2,3,False,N-termC11S12C18S20,Q9NRJ4_2_23_5_2_False_N-termC11S12C18S20
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,n:42.0106@n(1.0000)YRDPEAASPGAPSR;,NaN,NaN,NaN,1,0,1,False,N-term,O43581_2_15_1_0_False_N-term

In [130]:
raw_columns = [element for element in df_combined.columns if 'raw' in element]
print(raw_columns)

log2_abs_coulmns = [element.replace("raw_abs_", "log2_abs_") for element in raw_columns]
print(log2_abs_coulmns)

log2_mean_coulmns = [element.replace("log2_abs", "log2_mean") for element in log2_abs_coulmns ]
log2_mean_coulmns = [re.sub(r"_r[1-9]", "", element) for element in log2_abs_coulmns]
log2_mean_coulmns = list(dict.fromkeys(log2_mean_coulmns))
print(log2_mean_coulmns)

log2_FC_columns = [element.replace("log2_abs", "log2_FC") for element in log2_mean_coulmns]
print(log2_FC_columns)

['WT_raw_abs_EGF_starve_r1', 'WT_raw_abs_EGF_2_r1', 'WT_raw_abs_EGF_2_r2', 'WT_raw_abs_EGF_10_r1', 'WT_raw_abs_EGF_10_r2', 'WT_raw_abs_EGF_25_r1', 'WT_raw_abs_EGF_25_r2', 'BRAFS151A_raw_abs_EGF_starve_r1', 'BRAFS151A_raw_abs_EGF_2_r1', 'BRAFS151A_raw_abs_EGF_2_r2', 'BRAFS151A_raw_abs_EGF_10_r1', 'BRAFS151A_raw_abs_EGF_10_r2', 'BRAFS151A_raw_abs_EGF_25_r1', 'BRAFS151A_raw_abs_EGF_25_r2', 'GAB1Y259A_raw_abs_EGF_starve_r1', 'GAB1Y259A_raw_abs_EGF_2_r1', 'GAB1Y259A_raw_abs_EGF_2_r2', 'GAB1Y259A_raw_abs_EGF_10_r1', 'GAB1Y259A_raw_abs_EGF_10_r2', 'GAB1Y259A_raw_abs_EGF_25_r1', 'GAB1Y259A_raw_abs_EGF_25_r2']
['WT_log2_abs_EGF_starve_r1', 'WT_log2_abs_EGF_2_r1', 'WT_log2_abs_EGF_2_r2', 'WT_log2_abs_EGF_10_r1', 'WT_log2_abs_EGF_10_r2', 'WT_log2_abs_EGF_25_r1', 'WT_log2_abs_EGF_25_r2', 'BRAFS151A_log2_abs_EGF_starve_r1', 'BRAFS151A_log2_abs_EGF_2_r1', 'BRAFS151A_log2_abs_EGF_2_r2', 'BRAFS151A_log2_abs_EGF_10_r1', 'BRAFS151A_log2_abs_EGF_10_r2', 'BRAFS151A_log2_abs_EGF_25_r1', 'BRAFS151A_log2_abs_EGF_25_r2', 'GAB1Y259A_log2_abs_EGF_starve_r1', 'GAB1Y259A_log2_abs_EGF_2_r1', 'GAB1Y259A_log2_abs_EGF_2_r2', 'GAB1Y259A_log2_abs_EGF_10_r1', 'GAB1Y259A_log2_abs_EGF_10_r2', 'GAB1Y259A_log2_abs_EGF_25_r1', 'GAB1Y259A_log2_abs_EGF_25_r2']
['WT_log2_abs_EGF_starve', 'WT_log2_abs_EGF_2', 'WT_log2_abs_EGF_10', 'WT_log2_abs_EGF_25', 'BRAFS151A_log2_abs_EGF_starve', 'BRAFS151A_log2_abs_EGF_2', 'BRAFS151A_log2_abs_EGF_10', 'BRAFS151A_log2_abs_EGF_25', 'GAB1Y259A_log2_abs_EGF_starve', 'GAB1Y259A_log2_abs_EGF_2', 'GAB1Y259A_log2_abs_EGF_10', 'GAB1Y259A_log2_abs_EGF_25']
['WT_log2_FC_EGF_starve', 'WT_log2_FC_EGF_2', 'WT_log2_FC_EGF_10', 'WT_log2_FC_EGF_25', 'BRAFS151A_log2_FC_EGF_starve', 'BRAFS151A_log2_FC_EGF_2', 'BRAFS151A_log2_FC_EGF_10', 'BRAFS151A_log2_FC_EGF_25', 'GAB1Y259A_log2_FC_EGF_starve', 'GAB1Y259A_log2_FC_EGF_2', 'GAB1Y259A_log2_FC_EGF_10', 'GAB1Y259A_log2_FC_EGF_25']

In [157]:
df_combined.fillna(0, inplace=True)
df_combined

for i in range(log2_abs_coulmns):
    df_combined[log2_abs_coulmns[i]] = np.where(
                                            df_combined[raw_columns[i]] > 0,
                                            np.log2(df_combined[raw_columns[i]]),
                                            np.nan)

TypeError: 'list' object cannot be interpreted as an integer

In [152]:
cell_line = ["WT", "BRAFS151A", "GAB1Y259A"]
condition = ["starve", "EGF_2", "EGF_10", "EGF_25"]

for line in cell_line:
    for cond in condition:
        columns = [element for element in log2_abs_coulmns if (line in element) and (f"{cond}_" in element)]

        mean_col_name = f"{line}_log2_mean_EGF_{cond}"
        # print(mean_col_name)
        if len(columns) == 1:
            print(1, columns, mean_col_name)
            df_combined[mean_col_name] = df_combined[[columns[0]]]
        else:
            print(2, columns, mean_col_name)
            df_combined[mean_col_name] = df_combined[columns].mean(axis=1)

df_combined.fillna(0, inplace=True)
df_combined

1 ['WT_log2_abs_EGF_starve_r1'] WT_log2_mean_EGF_starve
2 ['WT_log2_abs_EGF_2_r1', 'WT_log2_abs_EGF_2_r2'] WT_log2_mean_EGF_EGF_2
2 ['WT_log2_abs_EGF_10_r1', 'WT_log2_abs_EGF_10_r2'] WT_log2_mean_EGF_EGF_10
2 ['WT_log2_abs_EGF_25_r1', 'WT_log2_abs_EGF_25_r2'] WT_log2_mean_EGF_EGF_25
1 ['BRAFS151A_log2_abs_EGF_starve_r1'] BRAFS151A_log2_mean_EGF_starve
2 ['BRAFS151A_log2_abs_EGF_2_r1', 'BRAFS151A_log2_abs_EGF_2_r2'] BRAFS151A_log2_mean_EGF_EGF_2
2 ['BRAFS151A_log2_abs_EGF_10_r1', 'BRAFS151A_log2_abs_EGF_10_r2'] BRAFS151A_log2_mean_EGF_EGF_10
2 ['BRAFS151A_log2_abs_EGF_25_r1', 'BRAFS151A_log2_abs_EGF_25_r2'] BRAFS151A_log2_mean_EGF_EGF_25
1 ['GAB1Y259A_log2_abs_EGF_starve_r1'] GAB1Y259A_log2_mean_EGF_starve
2 ['GAB1Y259A_log2_abs_EGF_2_r1', 'GAB1Y259A_log2_abs_EGF_2_r2'] GAB1Y259A_log2_mean_EGF_EGF_2
2 ['GAB1Y259A_log2_abs_EGF_10_r1', 'GAB1Y259A_log2_abs_EGF_10_r2'] GAB1Y259A_log2_mean_EGF_EGF_10
2 ['GAB1Y259A_log2_abs_EGF_25_r1', 'GAB1Y259A_log2_abs_EGF_25_r2'] GAB1Y259A_log2_mean_EGF_EGF_25

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,WT_log2_mean_EGF_EGF_10,WT_log2_mean_EGF_EGF_25,BRAFS151A_log2_mean_EGF_starve,BRAFS151A_log2_mean_EGF_EGF_2,BRAFS151A_log2_mean_EGF_EGF_10,BRAFS151A_log2_mean_EGF_EGF_25,GAB1Y259A_log2_mean_EGF_starve,GAB1Y259A_log2_mean_EGF_EGF_2,GAB1Y259A_log2_mean_EGF_EGF_10,GAB1Y259A_log2_mean_EGF_EGF_25
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,0,...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,jaja,jaja,hola,jaja,jaja,jaja,hola,jaja,jaja,jaja

In [153]:
df_combined["WT_log2_abs_EGF_starve_r1"]

KeyError: 'WT_log2_abs_EGF_starve_r1'