In [1]:
import numpy as np
import pandas as pd
from numpy.core.defchararray import endswith

from src.utils import *

In [2]:
df_combined = pd.read_csv("Experiment/hme1_mutants_test/Data/Processed/20260709_combined_modified_peptide_renamed.tsv", sep="\t")
df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,BRAFS151A_localization_EGF_10_r2,BRAFS151A_localization_EGF_25_r1,BRAFS151A_localization_EGF_25_r2,GAB1Y259A_localization_EGF_starve_r1,GAB1Y259A_localization_EGF_2_r1,GAB1Y259A_localization_EGF_2_r2,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.3985)AGGKEAAS(...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6939)AGGKEAAS(...,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,M:15.9949@VSVINTVDTSHEDM(0.8966)IHDAQM(0.1034)...,NaN,M:15.9949@VSVINTVDTSHEDM(0.9445)IHDAQM(0.0555)...,M:15.9949@VSVINTVDTSHEDM(0.9210)IHDAQM(0.0790)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,NaN,NaN,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,n:42.0106@n(1.0000)WQGSNLGGTPVTHCK;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,n:42.0106@n(1.0000)YRDPEAASPGAPSR;,NaN,NaN,NaN

# Re define columns

In [3]:
# Re define some columns for how many sites are localized, which type of modification was localized and how many
# Number of modifications localized
df_combined["n_localized"] = df_combined["assigned_modifications"].str.split(",").str.len().fillna(0).astype(int)

# Number of SYT modification localized
df_combined["STY_localized"] = (df_combined["assigned_modifications"]
                                .str.split(",")
                                .apply(lambda x: sum(any(c in item for c in "TYS") for item in x) if isinstance(x, list) else 0)
                                )

# Number of other modifications localized
df_combined["other_localized"] = (df_combined["assigned_modifications"]
                                .str.split(",")
                                .apply(lambda x: sum(not any(c in item for c in "TYS") for item in x) if isinstance(x, list) else 0)
                                )

# True or False if all modifications where localized (both STY and other)
df_combined["all_localized"] = df_combined["STY_localized"].astype(int) + df_combined["other_localized"].astype(int) == df_combined["Charges"].str.split(",").str[0].astype(int)

# Re-annotation for the modifications localization
df_combined["assigned_modifications_clean"] = df_combined["assigned_modifications"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_combined["assigned_modifications_clean"] = df_combined["assigned_modifications_clean"].str.replace(r"\b(\d+)([A-Za-z])\b", r"\2\1", regex=True)
df_combined["assigned_modifications_clean"] = df_combined["assigned_modifications_clean"].str.replace(r",", "", regex=True)

# Offset the residue numbers in assigned_modifications_clean by site_start
# e.g. site_start=346, "S2T15Y18" -> "S348T361Y364"
def offset_modification_positions(row):
    mod_str = row["assigned_modifications_clean"]
    site_start = row["site_start"]

    if pd.isna(mod_str) or pd.isna(site_start) or mod_str == "":
        return mod_str

    # Find all (amino_acid_letter, position_number) pairs and offset the number
    offsetted = re.sub(
        r"([A-Za-z])(\d+)",
        lambda m: f"{m.group(1)}{int(m.group(2)) + int(site_start) - 1}",
        mod_str
    )
    return offsetted

df_combined["assigned_modifications_clean"] = df_combined.apply(offset_modification_positions, axis=1)

# Create the site column with all the information
df_combined["site"] = (df_combined["protein_Id"].astype(str) + "_"
                       + df_combined["site_start"].astype(str) + "_"
                       + df_combined["site_end"].astype(str) + "_"
                       + df_combined["n_localized"].astype(str) + "_"
                       + df_combined["STY_localized"].astype(str) + "_"
                       + df_combined["all_localized"].astype(str) + "_"
                       + df_combined["assigned_modifications_clean"])

df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2,n_localized,STY_localized,other_localized,all_localized,Assigned_Modifications_clean,site
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,NaN,NaN,NaN,NaN,2,2,0,True,S479S484,P0CG40_455_484_2_2_True_S479S484
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,1,1,0,False,S471,P0CG40_455_475_1_1_False_S471
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,2,2,0,True,S471S479,P0CG40_455_484_2_2_True_S471S479
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,0,0,0,False,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,NaN,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,2,2,0,True,S1364S1368,Q8WXD9_1345_1370_2_2_True_S1364S1368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,2,0,2,False,N-termM15,P55735_2_27_2_0_False_N-termM15
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,3,0,3,True,N-termM15M21,P55735_2_27_3_0_True_N-termM15M21
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,NaN,NaN,NaN,2,0,2,True,N-termC15,rev_Q17R98_2_16_2_0_True_N-termC15
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,5,2,3,False,N-termC12S13C19S21,Q9NRJ4_2_23_5_2_False_N-termC12S13C19S21
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,n:42.0106@n(1.0000)YRDPEAASPGAPSR;,NaN,NaN,NaN,1,0,1,False,N-term,O43581_2_15_1_0_False_N-term

## create new columns list

In [4]:
# Check wich are the names of the columns with raw calues
raw_columns = [element for element in df_combined.columns if 'raw' in element]
print(raw_columns)

# Create the colums for the log2 trasformation of the data
log2_abs_coulmns = [element.replace("raw:abs_", "log2:abs_") for element in raw_columns]
print(log2_abs_coulmns)

# Create the colums for the log2 means
log2_mean_coulmns = [element.replace("log2:abs", "log2:mean") for element in log2_abs_coulmns ]
log2_mean_coulmns = [re.sub(r"_r[1-9]", "", element) for element in log2_mean_coulmns]
log2_mean_coulmns = list(dict.fromkeys(log2_mean_coulmns))
print(log2_mean_coulmns)

# Create the colums for the log2_FC calculations
log2_FC_columns = [element.replace("log2:mean", "log2:FC") for element in log2_mean_coulmns]
print(log2_FC_columns)

['WT_raw:abs_EGF_starve_r1', 'WT_raw:abs_EGF_2_r1', 'WT_raw:abs_EGF_2_r2', 'WT_raw:abs_EGF_10_r1', 'WT_raw:abs_EGF_10_r2', 'WT_raw:abs_EGF_25_r1', 'WT_raw:abs_EGF_25_r2', 'BRAFS151A_raw:abs_EGF_starve_r1', 'BRAFS151A_raw:abs_EGF_2_r1', 'BRAFS151A_raw:abs_EGF_2_r2', 'BRAFS151A_raw:abs_EGF_10_r1', 'BRAFS151A_raw:abs_EGF_10_r2', 'BRAFS151A_raw:abs_EGF_25_r1', 'BRAFS151A_raw:abs_EGF_25_r2', 'GAB1Y259A_raw:abs_EGF_starve_r1', 'GAB1Y259A_raw:abs_EGF_2_r1', 'GAB1Y259A_raw:abs_EGF_2_r2', 'GAB1Y259A_raw:abs_EGF_10_r1', 'GAB1Y259A_raw:abs_EGF_10_r2', 'GAB1Y259A_raw:abs_EGF_25_r1', 'GAB1Y259A_raw:abs_EGF_25_r2']
['WT_log2:abs_EGF_starve_r1', 'WT_log2:abs_EGF_2_r1', 'WT_log2:abs_EGF_2_r2', 'WT_log2:abs_EGF_10_r1', 'WT_log2:abs_EGF_10_r2', 'WT_log2:abs_EGF_25_r1', 'WT_log2:abs_EGF_25_r2', 'BRAFS151A_log2:abs_EGF_starve_r1', 'BRAFS151A_log2:abs_EGF_2_r1', 'BRAFS151A_log2:abs_EGF_2_r2', 'BRAFS151A_log2:abs_EGF_10_r1', 'BRAFS151A_log2:abs_EGF_10_r2', 'BRAFS151A_log2:abs_EGF_25_r1', 'BRAFS151A_log2:abs_EGF_25_r2', 'GAB1Y259A_log2:abs_EGF_starve_r1', 'GAB1Y259A_log2:abs_EGF_2_r1', 'GAB1Y259A_log2:abs_EGF_2_r2', 'GAB1Y259A_log2:abs_EGF_10_r1', 'GAB1Y259A_log2:abs_EGF_10_r2', 'GAB1Y259A_log2:abs_EGF_25_r1', 'GAB1Y259A_log2:abs_EGF_25_r2']
['WT_log2:mean_EGF_starve', 'WT_log2:mean_EGF_2', 'WT_log2:mean_EGF_10', 'WT_log2:mean_EGF_25', 'BRAFS151A_log2:mean_EGF_starve', 'BRAFS151A_log2:mean_EGF_2', 'BRAFS151A_log2:mean_EGF_10', 'BRAFS151A_log2:mean_EGF_25', 'GAB1Y259A_log2:mean_EGF_starve', 'GAB1Y259A_log2:mean_EGF_2', 'GAB1Y259A_log2:mean_EGF_10', 'GAB1Y259A_log2:mean_EGF_25']
['WT_log2:FC_EGF_starve', 'WT_log2:FC_EGF_2', 'WT_log2:FC_EGF_10', 'WT_log2:FC_EGF_25', 'BRAFS151A_log2:FC_EGF_starve', 'BRAFS151A_log2:FC_EGF_2', 'BRAFS151A_log2:FC_EGF_10', 'BRAFS151A_log2:FC_EGF_25', 'GAB1Y259A_log2:FC_EGF_starve', 'GAB1Y259A_log2:FC_EGF_2', 'GAB1Y259A_log2:FC_EGF_10', 'GAB1Y259A_log2:FC_EGF_25']

# Data clean up
## Remove rows without PTM and site not detected in the starvation

In [8]:
# Remove rows without PTM
df_combined = df_combined[df_combined.assigned_modifications_clean.notna()]
df_combined

# Drop rows where site is not detected in the starvation control
df_combined = df_combined[df_combined["WT_raw:abs_EGF_starve_r1"] != 0]
df_combined = df_combined[df_combined["BRAFS151A_raw:abs_EGF_starve_r1"] != 0]
df_combined = df_combined[df_combined["GAB1Y259A_raw:abs_EGF_starve_r1"] != 0]

df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2,n_localized,STY_localized,other_localized,all_localized,Assigned_Modifications_clean,site
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,STY:79.9663@AAAAAAAAT(0.0281)MALAAPS(0.5714)S(...,STY:79.9663@AAAAAAAAT(0.0236)MALAAPS(0.5303)S(...,STY:79.9663@AAAAAAAAT(0.0208)MALAAPS(0.5692)S(...,STY:79.9663@AAAAAAAAT(0.0295)MALAAPS(0.8855)S(...,2,2,0,True,S142S148,Q9NQS7_127_154_2_2_True_S142S148
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,STY:79.9663@AAAAAAT(0.0969)APPS(0.9031)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0889)APPS(0.9111)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0607)APPS(0.9393)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0569)APPS(0.9431)PGPAQPGPR;,1,1,0,False,S161,Q6SPF0_151_170_1_1_False_S161
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,STY:79.9663@AAAAAPAS(0.0183)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0184)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0182)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0182)EDEDDEDDEDDEDDDDDE...,1,1,0,False,S206,P19338_177_217_1_1_False_S206
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,STY:79.9663@AAAAAPAS(0.0188)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0186)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0193)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0196)EDEDDEDDEDDEDDDDDE...,2,1,1,False,S206M211,P19338_177_217_2_1_False_S206M211
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,STY:79.9663@AAAAAPAS(0.9430)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9450)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9440)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9438)EDEDDEDDEDDEDDDDDE...,1,1,0,False,S184,P19338_177_217_1_1_False_S184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,1,0,1,False,N-term,P38159_2_9_1_0_False_N-term
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,1,0,1,False,N-term,Q9UBE0_2_21_1_0_False_N-term
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,1,0,1,False,N-term,P55735_2_27_1_0_False_N-term
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.0599)IHDAQM(0.9401)...,M:15.9949@VSVINTVDTSHEDM(0.0945)IHDAQM(0.9055)...,M:15.9949@VSVINTVDTSHEDM(0.2488)IHDAQM(0.7512)...,M:15.9949@VSVINTVDTSHEDM(0.0638)IHDAQM(0.9362)...,2,0,2,False,N-termM21,P55735_2_27_2_0_False_N-termM21
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,2,0,2,False,N-termM15,P55735_2_27_2_0_False_N-termM15

## remove sites when site is not detected for any of the replicates of a time point

In [9]:
replicates = [element for element in raw_columns if "starve" not in element]
replicates

replicates = list(set([element.replace("_r1", "").replace("_r2", "") for element in replicates]))

suffixes = ["_r1", "_r2"]

# Drop rows if the phosphosite was not detected in the 2 replicates for any time point and any condition
for condition in replicates:
    mask = (
        (df_combined[f"{condition}{suffixes[0]}"] == 0) &
        (df_combined[f"{condition}{suffixes[1]}"] == 0)
    )
    df_combined = df_combined.drop(df_combined[mask].index)

df_combined

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2,n_localized,STY_localized,other_localized,all_localized,Assigned_Modifications_clean,site
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,STY:79.9663@AAAAAAAAT(0.0281)MALAAPS(0.5714)S(...,STY:79.9663@AAAAAAAAT(0.0236)MALAAPS(0.5303)S(...,STY:79.9663@AAAAAAAAT(0.0208)MALAAPS(0.5692)S(...,STY:79.9663@AAAAAAAAT(0.0295)MALAAPS(0.8855)S(...,2,2,0,True,S142S148,Q9NQS7_127_154_2_2_True_S142S148
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,STY:79.9663@AAAAAAT(0.0969)APPS(0.9031)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0889)APPS(0.9111)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0607)APPS(0.9393)PGPAQPGPR;,STY:79.9663@AAAAAAT(0.0569)APPS(0.9431)PGPAQPGPR;,1,1,0,False,S161,Q6SPF0_151_170_1_1_False_S161
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,STY:79.9663@AAAAAPAS(0.0183)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0184)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0182)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0182)EDEDDEDDEDDEDDDDDE...,1,1,0,False,S206,P19338_177_217_1_1_False_S206
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,STY:79.9663@AAAAAPAS(0.0188)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0186)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0193)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.0196)EDEDDEDDEDDEDDDDDE...,2,1,1,False,S206M211,P19338_177_217_2_1_False_S206M211
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,STY:79.9663@AAAAAPAS(0.9430)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9450)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9440)EDEDDEDDEDDEDDDDDE...,STY:79.9663@AAAAAPAS(0.9438)EDEDDEDDEDDEDDDDDE...,1,1,0,False,S184,P19338_177_217_1_1_False_S184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,n:42.0106@n(1.0000)VEADRPGK;,1,0,1,False,N-term,P38159_2_9_1_0_False_N-term
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,n:42.0106@n(1.0000)VEKEEAGGGISEEEAAQYDR;,1,0,1,False,N-term,Q9UBE0_2_21_1_0_False_N-term
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,n:42.0106@n(1.0000)VSVINTVDTSHEDMIHDAQMDYYGTR;,1,0,1,False,N-term,P55735_2_27_1_0_False_N-term
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.0599)IHDAQM(0.9401)...,M:15.9949@VSVINTVDTSHEDM(0.0945)IHDAQM(0.9055)...,M:15.9949@VSVINTVDTSHEDM(0.2488)IHDAQM(0.7512)...,M:15.9949@VSVINTVDTSHEDM(0.0638)IHDAQM(0.9362)...,2,0,2,False,N-termM21,P55735_2_27_2_0_False_N-termM21
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,2,0,2,False,N-termM15,P55735_2_27_2_0_False_N-termM15

# Log2 calculation

In [10]:
# Log2 calculations
for i in range(len(raw_columns)):
    df_combined[log2_abs_coulmns[i]] = np.log2(df_combined[raw_columns[i]])
    df_combined.replace(-np.inf, np.nan, inplace=True)

df_combined

/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
/Users/ignacionavascamacho/miniconda3/envs/TMT_Data_analysis/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,BRAFS151A_log2:abs_EGF_10_r2,BRAFS151A_log2:abs_EGF_25_r1,BRAFS151A_log2:abs_EGF_25_r2,GAB1Y259A_log2:abs_EGF_starve_r1,GAB1Y259A_log2:abs_EGF_2_r1,GAB1Y259A_log2:abs_EGF_2_r2,GAB1Y259A_log2:abs_EGF_10_r1,GAB1Y259A_log2:abs_EGF_10_r2,GAB1Y259A_log2:abs_EGF_25_r1,GAB1Y259A_log2:abs_EGF_25_r2
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,18.545938,18.884873,17.701277,18.360353,17.404435,NaN,18.440959,18.312102,18.300456,18.779039
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,21.264836,20.790005,NaN,20.705117,20.613376,20.635697,20.737282,20.648719,20.734119,20.525458
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,22.906988,21.620747,NaN,22.454001,22.291361,22.173243,22.088982,22.000975,22.585479,22.379405
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,19.332347,17.122350,NaN,18.357591,19.144796,17.597753,17.621160,18.527602,18.384963,18.200635
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,20.302062,18.031018,NaN,19.777153,19.752265,19.219910,19.380609,19.146100,20.369863,19.351746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,16.403975,15.818098,NaN,16.662986,15.887904,16.750522,16.651441,16.494387,16.061814,15.797002
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,16.188629,17.008281,NaN,17.079238,15.950803,17.243237,17.104987,16.614081,16.158007,15.698374
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,19.787973,19.922116,17.586662,21.122034,19.475092,21.591319,21.584465,20.950248,20.277471,20.180798
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,17.334670,16.916107,NaN,19.083808,17.052459,18.477506,18.140302,17.883630,17.821843,17.452447
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,15.983291,15.543055,NaN,17.240606,15.647012,16.912051,16.926662,16.389387,16.349076,16.171354

# log2 mean and sd calculation

In [11]:
# log2 mean calculations
log2_colums = list(([element.replace("_r1", "").replace("_r2", "") for element in log2_abs_coulmns]))
log2_colums = list(dict.fromkeys(log2_colums))

suffixes = ["_r1", "_r2"]

# Drop rows if the phosphosite was not detected in the 2 replicates for any time point and any condition
print("lo2_mean calculations")
for i in range(len(log2_mean_coulmns)):
    if "starve" in log2_mean_coulmns[i]:
        col = f"{log2_colums[i]}{suffixes[0]}"
        print(f"From: {col} to {log2_mean_coulmns[i]}")
        df_combined[log2_mean_coulmns[i]] = df_combined[col]
    else:
        col1 = f"{log2_colums[i]}{suffixes[0]}"
        col2 = f"{log2_colums[i]}{suffixes[1]}"
        print(f"From: {col1} and {col2} to {log2_mean_coulmns[i]}")
        df_combined[log2_mean_coulmns[i]] = np.nanmean(df_combined[[col1, col2]], axis=1)

# log2 sd calculations

log2_sd_columns = [element.replace("mean", "sd") for element in log2_mean_coulmns]
print("\nlog2 sd calculations")
for i in range(len(log2_sd_columns)):
    if "starve" in log2_sd_columns[i]:
        col = f"{log2_colums[i]}{suffixes[0]}"
        print(f"From: {col} to {log2_sd_columns[i]}")
        df_combined[log2_sd_columns[i]] = 0
    else:
        col1 = f"{log2_colums[i]}{suffixes[0]}"
        col2 = f"{log2_colums[i]}{suffixes[1]}"
        print(f"From: {col1} and {col2} to {log2_sd_columns[i]}")
        df_combined[log2_sd_columns[i]] = np.std(df_combined[[col1, col2]], axis=1)

df_combined

lo2_mean calculations
From: WT_log2:abs_EGF_starve_r1 to WT_log2:mean_EGF_starve
From: WT_log2:abs_EGF_2_r1 and WT_log2:abs_EGF_2_r2 to WT_log2:mean_EGF_2
From: WT_log2:abs_EGF_10_r1 and WT_log2:abs_EGF_10_r2 to WT_log2:mean_EGF_10
From: WT_log2:abs_EGF_25_r1 and WT_log2:abs_EGF_25_r2 to WT_log2:mean_EGF_25
From: BRAFS151A_log2:abs_EGF_starve_r1 to BRAFS151A_log2:mean_EGF_starve
From: BRAFS151A_log2:abs_EGF_2_r1 and BRAFS151A_log2:abs_EGF_2_r2 to BRAFS151A_log2:mean_EGF_2
From: BRAFS151A_log2:abs_EGF_10_r1 and BRAFS151A_log2:abs_EGF_10_r2 to BRAFS151A_log2:mean_EGF_10
From: BRAFS151A_log2:abs_EGF_25_r1 and BRAFS151A_log2:abs_EGF_25_r2 to BRAFS151A_log2:mean_EGF_25
From: GAB1Y259A_log2:abs_EGF_starve_r1 to GAB1Y259A_log2:mean_EGF_starve
From: GAB1Y259A_log2:abs_EGF_2_r1 and GAB1Y259A_log2:abs_EGF_2_r2 to GAB1Y259A_log2:mean_EGF_2
From: GAB1Y259A_log2:abs_EGF_10_r1 and GAB1Y259A_log2:abs_EGF_10_r2 to GAB1Y259A_log2:mean_EGF_10
From: GAB1Y259A_log2:abs_EGF_25_r1 and GAB1Y259A_log2:abs_EGF_25_r2 to GAB1Y259A_log2:mean_EGF_25

log2 sd calculations
From: WT_log2:abs_EGF_starve_r1 to WT_log2:sd_EGF_starve
From: WT_log2:abs_EGF_2_r1 and WT_log2:abs_EGF_2_r2 to WT_log2:sd_EGF_2
From: WT_log2:abs_EGF_10_r1 and WT_log2:abs_EGF_10_r2 to WT_log2:sd_EGF_10
From: WT_log2:abs_EGF_25_r1 and WT_log2:abs_EGF_25_r2 to WT_log2:sd_EGF_25
From: BRAFS151A_log2:abs_EGF_starve_r1 to BRAFS151A_log2:sd_EGF_starve
From: BRAFS151A_log2:abs_EGF_2_r1 and BRAFS151A_log2:abs_EGF_2_r2 to BRAFS151A_log2:sd_EGF_2
From: BRAFS151A_log2:abs_EGF_10_r1 and BRAFS151A_log2:abs_EGF_10_r2 to BRAFS151A_log2:sd_EGF_10
From: BRAFS151A_log2:abs_EGF_25_r1 and BRAFS151A_log2:abs_EGF_25_r2 to BRAFS151A_log2:sd_EGF_25
From: GAB1Y259A_log2:abs_EGF_starve_r1 to GAB1Y259A_log2:sd_EGF_starve
From: GAB1Y259A_log2:abs_EGF_2_r1 and GAB1Y259A_log2:abs_EGF_2_r2 to GAB1Y259A_log2:sd_EGF_2
From: GAB1Y259A_log2:abs_EGF_10_r1 and GAB1Y259A_log2:abs_EGF_10_r2 to GAB1Y259A_log2:sd_EGF_10
From: GAB1Y259A_log2:abs_EGF_25_r1 and GAB1Y259A_log2:abs_EGF_25_r2 to GAB1Y259A_log2:sd_EGF_25

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,WT_log2:sd_EGF_10,WT_log2:sd_EGF_25,BRAFS151A_log2:sd_EGF_starve,BRAFS151A_log2:sd_EGF_2,BRAFS151A_log2:sd_EGF_10,BRAFS151A_log2:sd_EGF_25,GAB1Y259A_log2:sd_EGF_starve,GAB1Y259A_log2:sd_EGF_2,GAB1Y259A_log2:sd_EGF_10,GAB1Y259A_log2:sd_EGF_25
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,0.000000,0.921718,0,0.014396,0.420136,0.591798,0,0.000000,0.064428,0.239291
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,0.008323,0.167532,0,0.234725,0.334199,0.000000,0,0.011161,0.044282,0.104331
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,0.646713,0.382206,0,0.000000,0.546733,0.000000,0,0.059059,0.044004,0.103037
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,0.146535,0.941158,0,0.342782,0.929512,0.000000,0,0.773522,0.453221,0.092164
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,0.480132,0.726576,0,0.000000,0.735416,0.000000,0,0.266177,0.117255,0.509059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,0.421174,0.471986,0,0.000000,0.000000,0.000000,0,0.431309,0.078527,0.132406
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,0.364974,0.691439,0,0.000000,0.228855,0.000000,0,0.646217,0.245453,0.229817
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,0.402976,0.725010,0,0.046286,0.346854,1.167727,0,1.058114,0.317108,0.048337
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,0.313172,0.429366,0,0.152154,0.267531,0.000000,0,0.712524,0.128336,0.184698
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,0.241425,0.000000,0,0.193388,0.153414,0.000000,0,0.632520,0.268637,0.088861

# Log2 FC claculation

In [12]:
for i in range(len(log2_FC_columns)):
    column = log2_FC_columns[i]
    information = column.split("_")
    cell = information[0]
    condition = information[-2]
    time_point = information[-1]

    control = [element for element in log2_mean_coulmns if cell in element and condition in element and element.endswith("starve")]
    condition = [element for element in log2_mean_coulmns if cell in element and condition in element and element.endswith(time_point)]

    print(f"For {log2_FC_columns[i]} use: {control[0]} and {condition[0]}")

    df_combined[log2_FC_columns[i]] = df_combined[condition[0]] - df_combined[control[0]]

df_combined

For WT_log2:FC_EGF_starve use: WT_log2:mean_EGF_starve and WT_log2:mean_EGF_starve
For WT_log2:FC_EGF_2 use: WT_log2:mean_EGF_starve and WT_log2:mean_EGF_2
For WT_log2:FC_EGF_10 use: WT_log2:mean_EGF_starve and WT_log2:mean_EGF_10
For WT_log2:FC_EGF_25 use: WT_log2:mean_EGF_starve and WT_log2:mean_EGF_25
For BRAFS151A_log2:FC_EGF_starve use: BRAFS151A_log2:mean_EGF_starve and BRAFS151A_log2:mean_EGF_starve
For BRAFS151A_log2:FC_EGF_2 use: BRAFS151A_log2:mean_EGF_starve and BRAFS151A_log2:mean_EGF_2
For BRAFS151A_log2:FC_EGF_10 use: BRAFS151A_log2:mean_EGF_starve and BRAFS151A_log2:mean_EGF_10
For BRAFS151A_log2:FC_EGF_25 use: BRAFS151A_log2:mean_EGF_starve and BRAFS151A_log2:mean_EGF_25
For GAB1Y259A_log2:FC_EGF_starve use: GAB1Y259A_log2:mean_EGF_starve and GAB1Y259A_log2:mean_EGF_starve
For GAB1Y259A_log2:FC_EGF_2 use: GAB1Y259A_log2:mean_EGF_starve and GAB1Y259A_log2:mean_EGF_2
For GAB1Y259A_log2:FC_EGF_10 use: GAB1Y259A_log2:mean_EGF_starve and GAB1Y259A_log2:mean_EGF_10
For GAB1Y259A_log2:FC_EGF_25 use: GAB1Y259A_log2:mean_EGF_starve and GAB1Y259A_log2:mean_EGF_25

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,WT_log2:FC_EGF_10,WT_log2:FC_EGF_25,BRAFS151A_log2:FC_EGF_starve,BRAFS151A_log2:FC_EGF_2,BRAFS151A_log2:FC_EGF_10,BRAFS151A_log2:FC_EGF_25,GAB1Y259A_log2:FC_EGF_starve,GAB1Y259A_log2:FC_EGF_2,GAB1Y259A_log2:FC_EGF_10,GAB1Y259A_log2:FC_EGF_25
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,-0.808449,-0.179979,0.0,0.888322,0.803156,0.130157,0.0,-0.955918,0.016177,0.179395
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,0.293958,0.354369,0.0,-0.962931,-0.290644,-0.431276,0.0,-0.080581,-0.012117,-0.075329
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,0.023431,0.330201,0.0,-2.574105,-0.605887,-1.345394,0.0,-0.221699,-0.409022,0.028441
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,0.157587,0.527729,0.0,-1.980528,-0.572586,-1.853071,0.0,0.013684,-0.283210,-0.064792
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,0.521452,0.545618,0.0,-2.079285,-0.628950,-2.164579,0.0,-0.291065,-0.513799,0.083652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,0.557558,0.517346,0.0,-1.805978,-1.245894,-1.831771,0.0,-0.343773,-0.090072,-0.733578
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,-0.031908,0.296446,0.0,1.159700,-0.228971,0.361825,0.0,-0.482218,-0.219705,-1.151048
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,0.433357,-0.597662,0.0,-0.829129,-1.267637,-2.648075,0.0,-0.588828,0.145323,-0.892899
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,0.577535,0.226112,0.0,-1.140735,-0.959473,-1.110505,0.0,-1.318825,-1.071842,-1.446663
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,0.444736,0.413445,0.0,-1.338201,-1.002712,-1.289534,0.0,-0.961074,-0.582581,-0.980391

In [13]:
# df_combined.to_cs v("Experiment/hme1_mutants_test/Data/Processed/Mutant_cell_lines_test.tsv", sep = "\t", index = False)
df_combined[df_combined["protein_name"] == "EGFR"]

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,WT_log2:FC_EGF_10,WT_log2:FC_EGF_25,BRAFS151A_log2:FC_EGF_starve,BRAFS151A_log2:FC_EGF_2,BRAFS151A_log2:FC_EGF_10,BRAFS151A_log2:FC_EGF_25,GAB1Y259A_log2:FC_EGF_starve,GAB1Y259A_log2:FC_EGF_2,GAB1Y259A_log2:FC_EGF_10,GAB1Y259A_log2:FC_EGF_25
6907,P00533,EGFR,Epidermal growth factor receptor,ALMDEEDMDDVVDADEYLIPQQGFFSSPSTSR,ALMDEEDMDDVVDADEYLIPQQGFFSS[79.9663]PSTSR,1000,1031,32,"3,4",27S(79.9663),...,0.372351,0.309673,0.0,0.106426,-0.045497,-0.321282,0.0,-0.086069,0.167171,0.232563
29638,P00533,EGFR,Epidermal growth factor receptor,ELVEPLTPSGEAPNQALLR,ELVEPLT[79.9663]PSGEAPNQALLR,687,705,19,"2,3",7T(79.9663),...,1.475592,1.932747,0.0,0.701247,1.803206,1.762330,0.0,0.345767,1.840099,2.096652
46656,P00533,EGFR,Epidermal growth factor receptor,GNMYYENSYALAVLSNYDANK,GNM[15.9949]YYENSYALAVLSNYDANK,109,129,21,2,3M(15.9949),...,0.141524,0.345571,0.0,-0.658300,-0.184595,-0.414785,0.0,-0.677900,-0.551871,-0.788894
49049,P00533,EGFR,Epidermal growth factor receptor,GSHQISLDNPDYQQDFFPK,GSHQISLDNPDY[79.9663]QQDFFPK,1161,1179,19,"2,3",12Y(79.9663),...,1.437734,1.674039,0.0,1.081190,1.480320,1.468066,0.0,1.031315,1.269735,1.018922
49050,P00533,EGFR,Epidermal growth factor receptor,GSHQISLDNPDYQQDFFPK,GSHQIS[79.9663]LDNPDYQQDFFPK,1161,1179,19,"2,3",6S(79.9663),...,-0.636864,0.610763,0.0,1.032152,0.302674,0.194037,0.0,0.818855,0.157710,-0.272984
49546,P00533,EGFR,Epidermal growth factor receptor,GSTAENAEYLR,GSTAENAEY[79.9663]LR,1189,1199,11,2,9Y(79.9663),...,1.491708,1.757606,0.0,0.186657,1.192369,0.849501,0.0,0.807667,1.229890,1.246740
89746,P00533,EGFR,Epidermal growth factor receptor,MHLPSPTDSNFYR,MHLPS[79.9663]PTDSNFYR,987,999,13,"2,3",5S(79.9663),...,-0.665776,0.019249,0.0,2.996628,2.450227,2.815477,0.0,0.168176,0.515200,0.876470