# LFQ data treatment

This code will work with the LFQ data provided by the FGCZ.

Initial working file for each experiment is the full combuned_modified_peptide

**First step is to rename the files to have a unified labeling system** -> (CellLine)_ (Data:Type)_ (Treatment)_ (TimePoint)_ (Replicate)

All the data transformation and statistics I am going to do starting from that initial "raw_data" file.

In [2]:
import pandas as pd

from src.column_spec import ColumnSpec
from src.lfq_pretreatment import *
from src.transformations import *

# mutants_test = pd.read_csv("../../data/hTERT_HME1_mutants_test_sample.tsv", sep="\t")
mutants_test = pd.read_csv(
    "../../Experiment/hme1_mutants_test/Data/Processed/20260709_combined_modified_peptide_renamed.tsv", sep="\t")
# mutants_test = pd.read_csv("../../Experiment/hme1_mutants_test/Data/20260429_hTERT_HME1_mutants_test.tsv", sep="\t")
mutants_test

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,BRAFS151A_localization_EGF_10_r2,BRAFS151A_localization_EGF_25_r1,BRAFS151A_localization_EGF_25_r2,GAB1Y259A_localization_EGF_starve_r1,GAB1Y259A_localization_EGF_2_r1,GAB1Y259A_localization_EGF_2_r2,GAB1Y259A_localization_EGF_10_r1,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.3985)AGGKEAAS(...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6939)AGGKEAAS(...,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,M:15.9949@VSVINTVDTSHEDM(0.8966)IHDAQM(0.1034)...,NaN,M:15.9949@VSVINTVDTSHEDM(0.9445)IHDAQM(0.0555)...,M:15.9949@VSVINTVDTSHEDM(0.9210)IHDAQM(0.0790)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9402)IHDAQM(0.0598)...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,NaN,NaN,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,n:42.0106@n(1.0000)WQGSNLGGTPVTHCK;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,n:42.0106@n(1.0000)YRDPEAASPGAPSR;,NaN,NaN,NaN

## Extracting metadata
Estracting necessary metadata as:
- n_localized
- STY_localized
- other_ocalized
- assigned_modification_clean
- sty_positions
- site_index

In [3]:
mutants_test_preprocessing = add_modification_metadata(mutants_test, mod_col= "Assigned_Modifications")
mutants_test_preprocessing

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_localization_EGF_10_r2,GAB1Y259A_localization_EGF_25_r1,GAB1Y259A_localization_EGF_25_r2,n_localized,STY_localized,other_localized,assigned_modifications_clean,sty_positions,site_index,site
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,NaN,NaN,NaN,2,2,0,S479S484,S479S484,P0CG40_455_484_2_2_S479S484,P0CG40_455_484_2_2_S479S484~AAAAAAAAAAAAAAAASA...
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,1,1,0,S471,S471,P0CG40_455_475_1_1_S471,P0CG40_455_475_1_1_S471~AAAAAAAAAAAAAAAAsAGGK
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,NaN,STY:79.9663@AAAAAAAAAAAAAAAAS(0.7806)AGGKEAAS(...,STY:79.9663@AAAAAAAAAAAAAAAAS(0.6667)AGGKEAAS(...,2,2,0,S471S479,S471S479,P0CG40_455_484_2_2_S471S479,P0CG40_455_484_2_2_S471S479~AAAAAAAAAAAAAAAAsA...
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,0,0,0,NaN,None,Q8WXD9_1345_1372_0_0_0,Q8WXD9_1345_1372_0_0_0~AAAAAAAAAAAPPAPPEGASPGD...
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,NaN,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,STY:79.9663@AAAAAAAAAAAPPAPPEGAS(1.0000)PGDS(1...,2,2,0,S1364S1368,S1364S1368,Q8WXD9_1345_1370_2_2_S1364S1368,Q8WXD9_1345_1370_2_2_S1364S1368~AAAAAAAAAAAPPA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(0.9424)IHDAQM(0.0576)...,M:15.9949@VSVINTVDTSHEDM(0.9418)IHDAQM(0.0582)...,M:15.9949@VSVINTVDTSHEDM(0.9426)IHDAQM(0.0574)...,2,0,2,N-termM15,None,P55735_2_27_2_0_0,P55735_2_27_2_0_0~n[42.0106]VSVINTVDTSHEDmIHDA...
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,M:15.9949@VSVINTVDTSHEDM(1.0000)IHDAQM(1.0000)...,NaN,3,0,3,N-termM15M21,None,P55735_2_27_3_0_0,P55735_2_27_3_0_0~n[42.0106]VSVINTVDTSHEDmIHDA...
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,NaN,NaN,2,0,2,N-termC15,None,rev_Q17R98_2_16_2_0_0,rev_Q17R98_2_16_2_0_0~n[42.0106]WQGSNLGGTPVTHcK
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,5,2,3,N-termC12S13C19S21,S13S21,Q9NRJ4_2_23_5_2_S13S21,Q9NRJ4_2_23_5_2_S13S21~n[42.0106]YAAVEHGPVLcsD...
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,NaN,NaN,NaN,1,0,1,N-term,None,O43581_2_15_1_0_0,O43581_2_15_1_0_0~n[42.0106]YRDPEAASPGAPSR

## Data transformations
Run the full transformation pipeline on each dataset:
- n:reps
- raw:mean / raw:median / raw:sd / raw:cv
- log2:abs (zeros treated as NaN)
- log2:mean / log2:median / log2:sd
- log2:FC (fold change vs. starve)
- log2:scaled (max-normalised fold change, amplitude between -1 and 1)
- log2:zscore (per-site z-score of the temporal profile, computed per condition per cell line across the time series; removes amplitude, keeps shape)
- log2:pvalue (Welch t-test vs. starve)
- log2:FDR (Benjamini-Hochberg correction per treatment × timepoint)
- log2:adjustedFDR (-log10 transformation of the FDR, also called adjusted FDR or adjusted p-value)

`log2:zscore` is produced automatically by `run_all_transformations`. To add or re-apply it standalone on an already-transformed LFQ frame, use `add_zscore_normalization(df, cell_lines=..., conditions=...)` from `src.lfq_pretreatment`.

In [4]:
mutants_processed  = run_all_transformations(mutants_test_preprocessing,  cell_lines=["WT", "BRAFS151A", "GAB1Y259A"], data_type="raw:abs", conditions=['_EGF_'])

print(f"hme1_1: {mutants_test_preprocessing.shape} -> {mutants_processed.shape}")

[WT] Found 1 conditions, 4 (treatment, timepoint) groups.
[WT] Done. Added 57 columns.
[BRAFS151A] Found 1 conditions, 4 (treatment, timepoint) groups.
[BRAFS151A] Done. Added 56 columns.
[GAB1Y259A] Found 1 conditions, 4 (treatment, timepoint) groups.
[GAB1Y259A] Done. Added 56 columns.

All cell lines processed. Total columns: 80 -> 249
hme1_1: (175089, 80) -> (175089, 249)

In [5]:
# Quick check of the new per-site z-score columns (log2:zscore) produced by run_all_transformations.
# Each cell line's EGF time series is standardised independently per site: mean ~ 0, std ~ 1 across timepoints.
for _cl in ["WT", "BRAFS151A", "GAB1Y259A"]:
    _z = ColumnSpec.select(mutants_processed, cell_lines=[_cl], data_type="log2:zscore", conditions=["_EGF_"])
    print(f"{_cl}: {len(_z)} log2:zscore columns -> {_z}")

WT: 4 log2:zscore columns -> ['WT_log2:zscore_EGF_starve', 'WT_log2:zscore_EGF_2', 'WT_log2:zscore_EGF_10', 'WT_log2:zscore_EGF_25']
BRAFS151A: 4 log2:zscore columns -> ['BRAFS151A_log2:zscore_EGF_starve', 'BRAFS151A_log2:zscore_EGF_2', 'BRAFS151A_log2:zscore_EGF_10', 'BRAFS151A_log2:zscore_EGF_25']
GAB1Y259A: 4 log2:zscore columns -> ['GAB1Y259A_log2:zscore_EGF_starve', 'GAB1Y259A_log2:zscore_EGF_2', 'GAB1Y259A_log2:zscore_EGF_10', 'GAB1Y259A_log2:zscore_EGF_25']

In [14]:
# mutants_processed.to_csv("../../data/hTERT_HME1_mutants_test_sample_transformed.tsv", sep="\t", index=False)
# mutants_processed.to_csv("../../Experiment/hme1_mutants_test/Data/Processed/20260714_hTERT_HME1_mutants_processed.tsv", sep="\t", index=False)

## Merging Phosphosite Plus dataset information

In [15]:
functional_score_df = pd.read_csv("../../External_Data/Metadata/PhosphoSitePlus.tsv", sep="\t")
regulatory_sites = pd.read_csv("../../External_Data/Metadata/Phosphosite/Regulatory_sites.tsv", sep="\t")

print(f"functional_score_df columns: {functional_score_df.columns}")
print(f"regulatory_sites columns: {regulatory_sites.columns}")

functional_score_df columns: Index(['protein_Id', 'protein_name', 'prot_seq_position', 'aa', 'site',
       'functional_score', 'ms_lit', 'ERK_motif', 'ERK_ext_motif'],
      dtype='object')
regulatory_sites columns: Index(['GENE', 'protein_name', 'information', 'protein_Id', 'GENE_ID',
       'HU_CHR_LOC', 'ORGANISM', 'MOD_RSD', 'SITE_GRP_ID', 'SITE_+/-7_AA',
       'DOMAIN', 'ON_FUNCTION', 'ON_PROCESS', 'ON_PROT_INTERACT',
       'ON_OTHER_INTERACT', 'PMIDs', 'LT_LIT', 'MS_LIT', 'MS_CST', 'NOTES'],
      dtype='object')

In [16]:
df_with_extra_info = merge_functional_score(df = mutants_processed,
                                            phosphosite_df = functional_score_df,
                                            ph_residue ="aa",
                                            ph_position = "prot_seq_position")
df_with_extra_info = merge_phosphoplus_info(df = df_with_extra_info,
                                            phosphosite_df = functional_score_df,
                                            ph_residue ="aa",
                                            ph_position = "prot_seq_position",
                                            adding_info = ["ERK_motif"])
df_with_extra_info = merge_phosphoplus_info(df = df_with_extra_info,
                                            phosphosite_df = regulatory_sites,
                                            ph_residue ="aa",
                                            ph_position = "prot_seq_position",
                                            adding_info = ["ORGANISM", "ON_FUNCTION", "ON_PROCESS", "ON_PROT_INTERACT", 'ON_OTHER_INTERACT'],
                                            regulatory_sites= True)
df_with_extra_info

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_log2:adjustedFDR_EGF_2,GAB1Y259A_log2:adjustedFDR_EGF_10,GAB1Y259A_log2:adjustedFDR_EGF_25,functional_score,ERK_motif,ORGANISM,ON_FUNCTION,ON_PROCESS,ON_PROT_INTERACT,ON_OTHER_INTERACT
0,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAASAGGKEAAS[79.9663]GPNDS[79.9663],455,484,30,2,"25S(79.9663),30S(79.9663)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGK,AAAAAAAAAAAAAAAAS[79.9663]AGGK,455,475,21,2,17S(79.9663),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P0CG40,SP9,Transcription factor Sp9,AAAAAAAAAAAAAAAASAGGKEAASGPNDS,AAAAAAAAAAAAAAAAS[79.9663]AGGKEAAS[79.9663]GPNDS,455,484,30,2,"17S(79.9663),25S(79.9663)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSARQK,AAAAAAAAAAAPPAPPEGASPGDSARQK,1345,1372,28,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q8WXD9,CASKIN1,Caskin-1,AAAAAAAAAAAPPAPPEGASPGDSAR,AAAAAAAAAAAPPAPPEGAS[79.9663]PGDS[79.9663]AR,1345,1370,26,2,"20S(79.9663),24S(79.9663)",...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175085,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQM[15.994...,2,27,26,3,"N-term(42.0106),14M(15.9949),20M(15.9949)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175086,rev_Q17R98,rev_ZNF827,Zinc finger protein 827,WQGSNLGGTPVTHCK,n[42.0106]WQGSNLGGTPVTHC[57.0215]K,2,16,15,2,"N-term(42.0106),14C(57.0215)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175087,Q9NRJ4,TULP4,Tubby-related protein 4,YAAVEHGPVLCSDSNILCLSWK,n[42.0106]YAAVEHGPVLC[57.0215]S[79.9663]DSNILC...,2,23,22,2,"N-term(42.0106),11C(57.0215),12S(79.9663),18C(...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175088,O43581,SYT7,Synaptotagmin-7,YRDPEAASPGAPSR,n[42.0106]YRDPEAASPGAPSR,2,15,14,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# df_with_extra_info.to_csv("../../Experiment/hme1_mutants_test/Data/Processed/20260714_hTERT_HME1_mutants_processed_phPlus.tsv", sep="\t", index=False)

## Filtering

In [2]:
# df_with_extra_info = pd.read_csv("../../Experiment/hme1_mutants_test/Data/Processed/20260709_hTERT_HME1_mutants_processed_phPlus.tsv", sep="\t")

/var/folders/jj/dfknz6j944d69gcp558vh1j80000gn/T/ipykernel_26883/2610818829.py:1: DtypeWarning: Columns (243) have mixed types. Specify dtype option on import or set low_memory=False.
  df_with_extra_info = pd.read_csv("../../Experiment/hme1_mutants_test/Data/Processed/20260709_hTERT_HME1_mutants_processed_phPlus.tsv", sep="\t")

In [4]:
print(df_with_extra_info.shape)
filtering = filter_no_ptm(df_with_extra_info)
filtering = filter_not_detected_in_starve(filtering, cell_lines=["WT", "BRAFS151A", "GAB1Y259A"], conditions=['_EGF_'], data_type="raw:abs")
filtering = filter_missing_replicates(filtering, cell_lines=["WT", "BRAFS151A", "GAB1Y259A"], conditions=['_EGF_'], data_type="raw:abs")
filtering

(175089, 244)
filter_no_ptm: removed 72497 rows without PTM.
filter_not_detected_in_starve: removed 89118 rows absent from starvation control.
filter_missing_replicates: removed 2589 rows undetected across all replicates of a time point.

,protein_Id,protein_name,description,Peptide_Sequence,Modified_Sequence,site_start,site_end,Peptide_Length,Charges,Assigned_Modifications,...,GAB1Y259A_log2:adjustedFDR_EGF_2,GAB1Y259A_log2:adjustedFDR_EGF_10,GAB1Y259A_log2:adjustedFDR_EGF_25,functional_score,ERK_motif,ORGANISM,ON_FUNCTION,ON_PROCESS,ON_PROT_INTERACT,ON_OTHER_INTERACT
17,Q9NQS7,INCENP,Inner centromere protein,AAAAAAAATMALAAPSSPTPESPTMLTK,AAAAAAAATMALAAPS[79.9663]SPTPES[79.9663]PTMLTK,127,154,28,"2,3","16S(79.9663),22S(79.9663)",...,NaN,NaN,NaN,0.374684,False|True,NaN,NaN,NaN,NaN,NaN
38,Q6SPF0,SAMD1,Sterile alpha motif domain-containing protein 1,AAAAAATAPPSPGPAQPGPR,AAAAAATAPPS[79.9663]PGPAQPGPR,151,170,20,2,11S(79.9663),...,NaN,NaN,NaN,0.517348,True,NaN,NaN,NaN,NaN,NaN
43,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAMET...,177,217,41,3,30S(79.9663),...,NaN,NaN,NaN,NaN,False,human,intracellular localization,"cell cycle regulation; cell growth, induced",NaN,NaN
44,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPASEDEDDEDDEDDEDDDDDEEDDS[79.9663]EEEAM[1...,177,217,41,3,"30S(79.9663),35M(15.9949)",...,NaN,NaN,NaN,NaN,False,human,intracellular localization,"cell cycle regulation; cell growth, induced",NaN,NaN
45,P19338,NCL,Nucleolin,AAAAAPASEDEDDEDDEDDEDDDDDEEDDSEEEAMETTPAK,AAAAAPAS[79.9663]EDEDDEDDEDDEDDDDDEEDDSEEEAMET...,177,217,41,3,8S(79.9663),...,NaN,NaN,NaN,0.362476,False,human,intracellular localization,"cell cycle regulation; cell growth, induced",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175069,P38159,RBMX,"RNA-binding motif protein, X chromosome",VEADRPGK,n[42.0106]VEADRPGK,2,9,8,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175071,Q9UBE0,SAE1,SUMO-activating enzyme subunit 1,VEKEEAGGGISEEEAAQYDR,n[42.0106]VEKEEAGGGISEEEAAQYDR,2,21,20,2,N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175082,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQMDYYGTR,2,27,26,"2,3",N-term(42.0106),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175083,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDMIHDAQM[15.9949]DYYGTR,2,27,26,3,"N-term(42.0106),20M(15.9949)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175084,P55735,SEC13,Protein SEC13 homolog,VSVINTVDTSHEDMIHDAQMDYYGTR,n[42.0106]VSVINTVDTSHEDM[15.9949]IHDAQMDYYGTR,2,27,26,3,"N-term(42.0106),14M(15.9949)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# filtering.to_csv("../../Experiment/hme1_mutants_test/Data/Processed/20260709_hTERT_HME1_mutants_processed_phPlus_filtered.tsv", sep="\t", index=False)